/*
 * This Java source file was generated by the Gradle 'init' task.
 * Braxton Soto
 */
package edu.isu.cs2263.hw01;

import org.apache.commons.cli.*;

import java.io.File;

public class App {

    public static void main(String[] args) {
        File file = new File("");
    Options options = new Options();
    CommandLineParser parser = new DefaultParser();
    Option batch = Option.builder ("b").longOpt("batch")
            .argName("file")
            .hasArg(true)
            .required(false)
            .desc("batch file containing expressions to evaluate").build();
    Option output = Option.builder ("o").longOpt("output")
            .argName("file")
            .hasArg(true)
            .required(false)
            .desc("output file").build();




        options.addOption("h", "help", false, "print help message");
        options.addOption(output);
        options.addOption(batch);

        try {
            CommandLine cmd = parser.parse( options, args);


            if(cmd.hasOption("h")){
                HelpFormatter formatter = new HelpFormatter();
                System.out.println("Evaluate simple mathematical expressions");
                formatter.printHelp("Options", options);
                System.exit(0);
            }
            if (cmd.hasOption("b")){
                System.out.println("Batch File: "+ cmd.getOptionValue("b"));

            }
            if (cmd.hasOption("o")){
                System.out.println("Output File: " + cmd.getOptionValue("b"));
            }


        } catch (ParseException e) {
            e.printStackTrace();
        }

    }
}

